ibm-apic-instance:
  ibmapicinstance:
    name: apic-cluster
    spec:
      license:
        accept: true
        use: production
        license: L-RJON-C7QFWS
      version: 10.0.4.0-ifix1-54
      profile: n3xc14.m48